apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "minecraft-server.fullname" . }}-config
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
data:
  {{- if .Values.minecraft.serverProperties }}
  server.properties: |
    {{- range $key, $value := .Values.minecraft.serverProperties }}
    {{ $key }}={{ $value }}
    {{- end }}
  {{- end }}
