apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minecraft-server.fullname" . }}-secret
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
type: Opaque
data:
  rcon-password: {{ include "minecraft-server.rconPassword" . | b64enc | quote }}
