apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-server.fullname" . }}
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: minecraft
  selector:
    {{- include "minecraft-server.selectorLabels" . | nindent 4 }}
---
{{- if and .Values.rcon.enabled .Values.rcon.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-server.fullname" . }}-rcon
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: rcon
spec:
  type: {{ .Values.rcon.service.type }}
  ports:
    - port: {{ .Values.rcon.service.port }}
      targetPort: {{ .Values.rcon.port }}
      protocol: TCP
      name: rcon
  selector:
    {{- include "minecraft-server.selectorLabels" . | nindent 4 }}
{{- end }}
